# Development override for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up --watch

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      args:
        PUBLIC_SUPABASE_URL: http://kong:${KONG_HTTP_PORT}
        PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
        USERNAME: ${USERNAME:-appuser}
    environment:
      NODE_ENV: development
      PORT: ${APP_PORT:-3000}
      PUBLIC_SUPABASE_URL: http://kong:${KONG_HTTP_PORT}
      PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - "**/*.test.js"
            - "**/*.spec.js"
        - action: sync
          path: ./static
          target: /app/static
        - action: sync
          path: ./app.html
          target: /app/app.html
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./pnpm-lock.yaml
        - action: rebuild
          path: ./svelte.config.js
        - action: rebuild
          path: ./vite.config.js
        - action: rebuild
          path: ./.env*