# Prometheus Configuration for LaunchPadder Production Monitoring
# Collects metrics from all services for observability

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'launchpadder-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # LaunchPadder Web Application instances
  - job_name: 'launchpadder-web'
    static_configs:
      - targets: 
        - 'web-1:3000'
        - 'web-2:3000'
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Supabase services
  - job_name: 'supabase-auth'
    static_configs:
      - targets: ['auth:9999']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'supabase-rest'
    static_configs:
      - targets: ['rest:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'supabase-realtime'
    static_configs:
      - targets: ['realtime:4000']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'supabase-storage'
    static_configs:
      - targets: ['storage:5000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Health checks monitoring
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'web-1:3000'
        - 'web-2:3000'
    scrape_interval: 10s
    metrics_path: /api/health
    params:
      detailed: ['false']
    scrape_timeout: 5s

  # External service monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.openai.com/v1/models
        - https://api.stripe.com/v1/account
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'ssl-certificates'
    metrics_path: /probe
    params:
      module: [ssl_cert]
    static_configs:
      - targets:
        - your-domain.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://your-remote-storage-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://your-remote-storage-endpoint/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"