_format_version: "2.1"

services:
  - name: auth-v1-open
    url: http://auth:9999/
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/signup
          - /auth/v1/token
          - /auth/v1/verify
          - /auth/v1/recover
          - /auth/v1/resend
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - X-Requested-With
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  - name: auth-v1-open-keys
    url: http://auth:9999/
    routes:
      - name: auth-v1-open-keys
        strip_path: true
        paths:
          - /auth/v1/settings
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - apikey
            - X-Requested-With
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - apikey
            - X-Requested-With
            - Range
          exposed_headers:
            - X-Auth-Token
            - Content-Range
          credentials: true
          max_age: 3600

  - name: realtime-v1
    url: http://realtime:4000/socket/
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - apikey
            - X-Requested-With
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  - name: storage-v1
    url: http://storage:5000/
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - apikey
            - X-Requested-With
            - Range
          exposed_headers:
            - X-Auth-Token
            - Content-Range
          credentials: true
          max_age: 3600

  - name: health
    url: http://meta:8080/
    routes:
      - name: health-check
        strip_path: true
        paths:
          - /health
      - name: root
        strip_path: false
        paths:
          - /